[package]
name = "puck_liveview"
version = "0.1.0"
authors = ["teymour-aldridge <teymour.aldridge@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.10.2"
malvolio = { git = "https://github.com/lovelace-edu/lovelace", features = ["pub_fields"], branch = "main" }
puck = { path = "../puck" }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
maplit = "1.0.2"

[dev-dependencies]
insta = "1.7.1"
scraper = "0.12.0"
