[package]
name = "puck"
version = "0.1.0"
authors = ["teymour-aldridge <teymour.aldridge@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
httparse = "1.3.5"
thiserror = "1.0.24"
puck_codegen = { path = "../puck_codegen" }
url = "2.2.1"
derivative = "2.2.0"
sha-1 = "0.9.6"
base64 = "0.13.0"
byteorder = "1.4.3"
log = "0.4.14"
serde = { version = "1.0.126", features = ["derive"] }

[target.'cfg(target_arch="wasm32")'.dependencies]
proptest = { version = "1.0.0", optional = true }

[dev-dependencies]
itertools = "0.10.0"

[features]
_test_fuzzing = ["proptest"]
