name: Test

on:
  push:
    pull_request:
    branches:
      - staging
      - trying

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
          override: true
          components: rustfmt, clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Lint
        run: cargo clippy -- -D warnings

  main-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Lunatic
        run: curl https://i.jpillora.com/lunatic-solutions/lunatic@v0.3.1! | sudo bash
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-wasi
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: cargo test

  native-diffing-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Lunatic
        run: curl https://i.jpillora.com/lunatic-solutions/lunatic@v0.3.1! | sudo bash
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: false
          target: wasm32-wasi
      - uses: Swatinem/rust-cache@v1
      - name: Run native tests
        run: (cd puck_liveview && cargo test --features apply --target x86_64-unknown-linux-gnu)

  # Anyone who can fix this gets a metaphorical gold star.
  #
  #  autobahn-tests:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - name: Install Lunatic
  #        run: curl https://i.jpillora.com/lunatic-solutions/lunatic@v0.3.1! | sudo bash
  #      - uses: actions-rs/toolchain@v1
  #        with:
  #          toolchain: stable
  #          override: true
  #          target: wasm32-wasi
  #      - uses: actions/cache@v2
  #        with:
  #          path: |
  #            ~/.cargo/registry
  #            ~/.cargo/git
  #            target
  #          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
  #          restore-keys: |
  #            cargo-${{ runner.os }}-
  #      - run: ./scripts/server_test.sh

  bors-report:
    runs-on: ubuntu-latest

    needs:
      - main-tests
      - lint
      - native-diffing-tests

    steps:
      - name: Check
        run: |
          [ ${{ needs.lint.result }} == success ] &&
          [ ${{ needs.native-diffing-tests.result }} == success ] &&
          [ ${{ needs.main-tests.result }} == success ] || exit 1
